import Head from 'next/head';
import Link from 'next/link';
import Image from "next/image";

const Layout = ({ children, title = 'Crypto Tracker' }) => {
  return (
    <div className="layout">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="header">
        <Link href="/" passHref>
          <a>
            <Image className="coin_logo" src="/logo.png" alt="Logo" />
          </a>
        </Link>
      </header>
      <main>{children}</main>
    </div>
  );
};

export default Layout;
